"Violin",
"Guitar",
"Piano",
"Flute",
"Clarinet",
"Oboe",
"Trumpet",
"Organ",
"Horn",
"Synthesizer",
"Harpsicord",
"Vibraphone",
"Synthesizer Bass",
"Acoustic Bass",
"Electric Guitar",
;"Piano 1",
"Piano 2",
"Piano 4",
"Electric Piano 1",
"Electric Piano 2",
"Electric Piano 3",
;"Electric Piano 4",
"DX-7 Piano 1",
"DX-7 Piano 2",
;"DX-7 Piano 3",
;"Synth Piano",
"Harpsichord 1",
;"Harpsichord 2",
;"Clavicode 1",
"Clavicode 2",
"Marimba 1",
"Marimba 3",
;"Marimba 4",
;"Marimba 5",
;"Marimba 6",
;"Vibraphone 1",
;"Vibraphone 2",
"Vibraphone 3",
"Vibraphone 4",
"Xylophone 2",
"Bell 1",
;"Bell 3",
;"Space Bell 1",
"Chimes 1",
"Chimes 2",
;"Santool",
"Organ",
"Pipe Organ 1",
"Pipe Organ 2",
"Electric Organ 1",
"Accordion",
"Harmonica",
"Spanish Guitar 1",
"Spanish Guitar 2",
"Blues Guitar",
"Funny Guitar",
"Fuzz Guitar 1",
"Fuzz Guitar 3",
"Rock Guitar",
"Hardrock Guitar",
"Wanderer",
;"Rock Bass",
"Slide Guitar 1",
"Slide Guitar 2",
;"Slide Guitar 3",
"Bass 1",
"Bass 2",
"Cool Bass 1",
"Cool Bass 2",
"Rasp Bass",
;"Slap Bass 1",
"Slap Bass 2",
"Slap Bass 3",
"Short Bass",
;"Synth Bass 1",
"Synth Bass 2",
"Synth Bass 3",
"Electric Bass 1",
"Electric Bass 2",
"Electric Bass 3",
"Elastic Bass",
"Strings 1",
"Strings 2",
;"Strings 3",
"Jarre String",
"Synth String 1",
"Synth String 3",
"Heavy String",
"Violin",
;"Synth Violin",
"Harp",
"Bell Brass",
;"Brass 1",
"Brass 2",
"Brass 3",
"Trumpet 1",
"Trumpet 2",
"Trumpet 3",
"Synth Trumpet 1",
"Synth Trumpet 2",
;"Synth Trumpet 3",
"Trombone",
"Tuba 1",
"Tuba 2",
"Clarinet",
"Horn",
"Oboe",
"Saxophone 1",
"Saxophone 2",
"Saxophone 3",
"Flute 1", 
"Flute 2",
"Flute 3",
"Flute 4",
;"Flute 5",
"Synth Flute",
;"Piccolo",
"Synth 1",
"Synth 2",
"Synth 3",
"Synth 4",
"Synth 5",
"Synth Lead",
"New Synth",
;"Wow Synth",
;"MSX-PSG 1",
"MSX-PSG 2",
"Synth Sweep 1",
"Synth Sweep 2",
"Heavy Synth",
"Smad Synth",
"Dark Synth",
"Warmth 1",
"Warmth 2",
;"Chord",
"Alien 1",
"Alien 2",
"SE-Star",
"Sitar",
"Banjo",
"Koto 1",
"Koto 2",
"Steel Drum 1",
;"Mouth Harp",
"Harm drum",
"Bass Drum 1",
"Bass Drum 2",
"Chop 1",
"Chop 2",
"Electrons 1",
"Electrons 2",
"Electrons 3",
"Bell Percussion",
"Snare Drum",
"Steel Drum 2",
;"Open Hihat",
;"Closed Hihat",
"Synth Perc. 1",
"Synth Perc. 2",
"Comic",
"Space Piano",
"Acid Piano",
;"Piano 3",
"Harpsichord 3",
"Marimba 2",
"Bell 2",
"Synth Bell",
"Space Bell 2",
"Funk Organ",
"Laser Harp",
"Plucked 1",
"Plucked 2",
"Plucked 3",
;"Invasion",
;"Sonic 1",
"Sonic 2",
"Custom Voice 01",
"Custom Voice 02", 
"Custom Voice 03",
"Custom Voice 04",
"Custom Voice 05",
"Custom Voice 06",
"Custom Voice 07",
"Custom Voice 08",
"Custom Voice 09",
"Custom Voice 10",
"Custom Voice 11",
"Custom Voice 12",
"Custom Voice 13",
"Custom Voice 14",
"Custom Voice 15",
"Custom Voice 16"



	
	